[package]
name = "nom-teltonika"
version = "0.1.0"
edition = "2021"
description = "Teltonika protocol parser"
readme = "README.md"
repository = "https://github.com/DamianoPellegrini/nom-teltonika"
license = "MIT"
keywords = ["parser", "library", "binary", "teltonika", "protocol"]
categories = ["encoding", "parser-implementations"]
publish = true

[dependencies]
chrono = "0.4.23"
log = "0.4.17"
nom = "7.1.1"

[dev-dependencies]
hex = "0.4.3"
