name: Commits linting
on: push
jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: './.commitlintrc.yml'
